### ISSUE TITLE
wrong values not detected

### ISSUE THREAD

**Issue by boellner** [owfs/owfs#117]
Hello,
It happens that tempeature vales of every of my DS18B20 read out a wrong value that is not detected by crc. 
To better reproduce the error I made a test setup where I connected a lot of sensors to a long line.
Half of the displayed values are in the measurement range but show random false values that are not filtered out. What can be the issue and how to detect bad values?

![image](https://github.com/user-attachments/assets/53c30bd1-2072-492c-a3d9-32b269c10e16)

**Comment by ianka** [comment]
Are those sensors by chance all parasite powered? My guess is that they brownout and do random things because their supply voltage is too low in some situations.

**Comment by boellner** [comment]
Some sensors are parasitic powered, some not. The above screenshot is a worst case setup to show you the problem. In my "normal" setup I get this kind of errors occasionally.
I can live with network dropouts etc.
but bad receiving values in a valid range that are obviously false like in the picture above without being detected by the bus at all is a no-go for me. I have to rely on the values Thanks

**Comment by ianka** [comment]
The DS18B20 are calibrated but they aren't safe against brownouts. They can measure the temperature wrong then. There's nothing to correct on the bus or within OWFS when the sensor itself got it wrong already.

So you have to avoid brownouts. Power all the sensors.

**Comment by miccoli** [comment]
I agree with @ianka : if an inaccurate value gets on the DS18B20 scratchpad memory, there is no safeguard inside the one-wire protocol or OWFS to detect the anomaly.

You can work on the HW side (stress test sensors to detect faulty ones or check the "Powering the DS18B20" section in the [data sheet](https://www.analog.com/media/en/technical-documentation/data-sheets/ds18b20.pdf)). Sometimes HW problems can be mitigated by reading temperature values at lower resolution (9bit instead of 12bit), because temperature conversion times are much shorter.

On the SW side you can implemented anomaly detection algorithms.

**Comment by boellner** [comment]
ok, thank you all for the explanation
