### ISSUE TITLE
Setting Pulldown Slew Rate

### ISSUE THREAD

**Issue by chlangbein** [owfs/owfs#33]
Hello,
i use DS2482S-100 and DS2482-800 over i2c on a long bus. Is it possible to get and set the values 
Pulldown Slew Rate: 1.37V/μs 
Write-One Low Time: 11μs 
Data Sample Offset/Recovery: 10μs
found on guidelines for long networks ?  What default values are used ? Also put R-C filter in front, but currently random devices are not found.

Thanks in advance,
Christoph

**Comment by miccoli** [comment]
I'm closing this issue because unfortunately it has not received attention (and I'm not able to give advice on this matter).

While there is still no policy about how to define "acceptable" issues, I would define the present one as a question, which should better asked on the mailing list  <https://sourceforge.net/p/owfs/mailman/owfs-developers/>
where it has more chances to be answered.
